In [1]:
import yfinance as yf
import pandas as pd

In [2]:
sgb = yf.download("SGB=F", start="2015-01-01", 
                  auto_adjust=False, multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [3]:
sgb

             Adj Close       Close        High         Low        Open  Volume
Date
2015-01-02   70.207001   70.207001   70.207001   70.207001   70.207001      25
2015-01-05   67.499001   67.499001   67.499001   67.499001   67.499001       0
2015-01-06   66.156998   66.156998   66.156998   66.156998   66.156998       0
2015-01-07   64.683998   64.683998   64.683998   64.683998   64.683998       0
2015-01-08   64.959000   64.959000   64.959000   64.959000   64.959000       0
...                ...         ...         ...         ...         ...     ...
2026-04-27  195.966995  195.966995  195.966995  195.966995  195.966995       0
2026-04-28  194.923996  194.923996  194.923996  194.923996  194.923996       0
2026-04-29  195.432999  195.432999  195.432999  195.432999  195.432999       0
2026-04-30  195.526001  195.526001  195.526001  195.526001  195.526001       0
2026-05-01  160.671005  160.671005  160.671005  160.671005  160.671005       0

[2831 rows x 6 columns]

In [4]:
sgb.isnull().sum()

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [5]:
sgb = sgb[["Close"]].copy()
sgb.columns = ["mops_gasoil"]
sgb = sgb.reset_index()
sgb.columns = ["date", "mops_gasoil"]
sgb = sgb.set_index("date").sort_index()

In [6]:
# weekly aggregation (just close + mean since high/low/close are basically same)
weekly_sgb = sgb.resample("W-FRI").last()
weekly_sgb.columns = ["mops_gasoil"]
weekly_sgb["mops_gasoil_mean"] = sgb.resample("W-FRI").mean()

# Anchor to Monday
weekly_sgb.index = weekly_sgb.index - pd.Timedelta(days=4)
weekly_sgb.index.name = "week_start"

In [7]:
weekly_sgb.to_parquet("data/semi-cleaned/mops_gasoil_weekly.parquet")

In [8]:
weekly_sgb

            mops_gasoil  mops_gasoil_mean
week_start
2014-12-29    70.207001         70.207001
2015-01-05    64.002998         65.460399
2015-01-12    63.037998         62.772601
2015-01-19    62.953999         62.846499
2015-01-26    62.666000         62.762200
...                 ...               ...
2026-03-30   230.503998        204.551247
2026-04-06   194.065994        209.639999
2026-04-13   182.509003        191.773001
2026-04-20   195.337006        192.018002
2026-04-27   160.671005        188.504199

[592 rows x 2 columns]