In [1]:
import yfinance as yf
import pandas as pd

In [2]:
sgb = yf.download("SGB=F", start="2015-01-01", 
                  auto_adjust=False, multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [3]:
sgb

             Adj Close       Close        High         Low        Open  Volume
Date
2015-01-02   70.207001   70.207001   70.207001   70.207001   70.207001      25
2015-01-05   67.499001   67.499001   67.499001   67.499001   67.499001       0
2015-01-06   66.156998   66.156998   66.156998   66.156998   66.156998       0
2015-01-07   64.683998   64.683998   64.683998   64.683998   64.683998       0
2015-01-08   64.959000   64.959000   64.959000   64.959000   64.959000       0
...                ...         ...         ...         ...         ...     ...
2026-04-29  195.432999  195.432999  195.432999  195.432999  195.432999       0
2026-04-30  195.526001  195.526001  195.526001  195.526001  195.526001       0
2026-05-01  160.671005  160.671005  160.671005  160.671005  160.671005       0
2026-05-04  160.738007  160.738007  160.738007  160.738007  160.738007       0
2026-05-05  160.167999  160.167999  160.167999  160.167999  160.167999       0

[2833 rows x 6 columns]

In [4]:
sgb.isnull().sum()

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [5]:
sgb = sgb[["Close"]].copy()
sgb.columns = ["mops_gasoil"]
sgb = sgb.reset_index()
sgb.columns = ["date", "mops_gasoil"]
sgb = sgb.set_index("date").sort_index()

In [6]:
weekly_sgb = sgb.resample("W-TUE").agg(
    mops_gasoil_close=("mops_gasoil", "last"),
    mops_gasoil_mean=("mops_gasoil", "mean"),
)
# weekly_sgb.index = weekly_sgb.index + pd.Timedelta(days=3)
# weekly_sgb.index.name = "week_monday"

In [7]:
weekly_sgb

            mops_gasoil_close  mops_gasoil_mean
date
2015-01-06          66.156998         67.954333
2015-01-13          62.205002         63.842200
2015-01-20          62.869999         62.792000
2015-01-27          62.792999         62.830800
2015-02-03          68.064003         64.235201
...                       ...               ...
2026-04-07         223.309998        222.210499
2026-04-14         191.552994        196.905798
2026-04-21         190.561005        188.889404
2026-04-28         194.923996        194.638599
2026-05-05         160.167999        174.507202

[592 rows x 2 columns]

In [8]:
weekly_sgb.to_parquet("../data/semi-cleaned/mops_gasoil_weekly.parquet")